### ISSUE TITLE
Installation instructions for development

### ISSUE THREAD

**Issue by little-dude** [Cogitri/gxi#277]
I'd like to try to build `gxi` in "dev mode", ie

- without installing it under /usr/local
- without needing `sudo` (although that related to the previous point I guess)
- with the possibility to use a custom local `xi-editor` repo

Is this currently possible? If so, would you mind writing up some instructions to get started?

Thank you!

**Comment by Cogitri** [comment]
Thanks for the issue, I'll make some docs for this later this day! :) 

> * without installing it under /usr/local
> * without needing sudo (although that related to the previous point I guess)

For this you can do the following: Just do the install procedure as described in the README, but do `meson --prefix=<somedir> build`, to install it to some other directory. Sadly an installation via cargo doesn't work due to gxi needing some more files to run (but you can do this manually: do `cargo install` to install gxi and then copy `data/com.github.Cogitri.gxi.gschema.xml` to any dir of your liking, let's say `$HOME/Projects/gxi`. Then do `glib-compile-schemas $HOME/Projects/gxi`and then run gxi: `env  GSETTINGS_SCHEMA_DIR=$HOME/Projects/gxi gxi`

> with the possibility to use a custom local xi-editor repo

Hm, that'll be a bit harder. You can just remove the repo in `vendor/xi-editor` and replace it with yours if you want to for now.

**Comment by Cogitri** [comment]
Also, a few things to note which aren't necessarily related to this:

#266 is kind of broken right now, see the checklist

The current master branch does work properly, but gxi is rather inefficient due to the excessive use of spinlocks, so it usually just locks one CPU to 100% (this is greatly improved with xrl, thanks!)
